# Generated by Django 4.2.1 on 2023-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_level1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_info',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
