# Generated by Django 4.2.1 on 2023-06-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_student_level_delete_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.level'),
        ),
    ]
