# Generated by Django 4.2.1 on 2023-06-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
