# Generated by Django 4.2.1 on 2023-06-13 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('french', 'French'), ('arabic', 'Arabic'), ('mathematic', 'Mathematic'), ('ei', 'Ei'), ('hg', 'Hg'), ('pc', 'Pc'), ('svt', 'Svt')], max_length=120)),
                ('level', models.ManyToManyField(to='main.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
