# Generated by Django 4.2.1 on 2023-06-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_level_teacher_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='pdf_files/')),
                ('module', models.CharField(choices=[('french', 'French'), ('arabic', 'Arabic'), ('mathematic', 'Mathematic'), ('ei', 'Ei'), ('hg', 'Hg'), ('pc', 'Pc'), ('svt', 'Svt')], max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='level',
            name='file',
        ),
        migrations.RemoveField(
            model_name='level',
            name='module',
        ),
        migrations.RemoveField(
            model_name='level',
            name='title',
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=120),
        ),
    ]
