# Generated by Django 4.2.1 on 2023-06-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_lesson_remove_level_file_remove_level_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level'),
        ),
    ]
