# Generated by Django 4.2.1 on 2023-06-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_student_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
