# Generated by Django 4.2.1 on 2023-06-15 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_delete_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('2022', '2023'), ('2023', '2024')], max_length=120)),
                ('year_of_school', models.DateField()),
                ('french_grade', models.FloatField(blank=True)),
                ('arabic_grade', models.FloatField(blank=True)),
                ('mathematic_grade', models.FloatField(blank=True)),
                ('ei_grade', models.FloatField(blank=True)),
                ('hg_grade', models.FloatField(blank=True)),
                ('pc_grade', models.FloatField(blank=True)),
                ('svt_grade', models.FloatField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
