# Generated by Django 4.2.1 on 2023-06-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='year_of_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.year_study'),
        ),
    ]
