# Generated by Django 4.2.1 on 2023-06-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_year_study_alter_grade_year_of_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='semestre',
            field=models.CharField(choices=[('semestre1', 'Semestre1'), ('semestre2', 'Semestre2')], max_length=120),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom'),
        ),
    ]
