# Generated by Django 4.2.1 on 2023-06-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_grade_semestre_classroom_student_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.ManyToManyField(to='main.classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.module'),
        ),
    ]
