# Generated by Django 4.2.1 on 2023-06-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_module_alter_teacher_level_alter_teacher_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='level',
            new_name='classroom',
        ),
    ]
