# Generated by Django 4.2.1 on 2023-06-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_lesson_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
