# Generated by Django 4.2.1 on 2023-06-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_delete_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='pdf_files/')),
                ('module', models.CharField(choices=[('french', 'French'), ('arabic', 'Arabic'), ('mathematic', 'Mathematic'), ('ei', 'Ei'), ('hg', 'Hg'), ('pc', 'Pc'), ('svt', 'Svt')], max_length=120)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
            ],
        ),
    ]
