# Generated by Django 4.2.1 on 2023-06-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.education_level'),
        ),
    ]
