# Generated by Django 4.2.1 on 2023-06-15 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_level_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.level'),
        ),
    ]
