# Generated by Django 4.2.1 on 2023-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_module_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='level',
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.ManyToManyField(blank=True, null=True, to='main.level'),
        ),
    ]
