# Generated by Django 4.2.1 on 2023-06-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_module_level_module_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.ManyToManyField(blank=True, to='main.level'),
        ),
    ]
