# Generated by Django 4.2.1 on 2023-06-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_attendence_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_report',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.level'),
        ),
    ]
