# Generated by Django 4.2.1 on 2023-06-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_lesson_level_lesson_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence_report',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
