# Generated by Django 4.2.1 on 2023-06-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_student_attendence_report_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
