# Generated by Django 4.2.1 on 2023-06-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_rename_father_full_student_father_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classroom')),
                ('year_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.year_study')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
