# Generated by Django 4.2.1 on 2023-06-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom_grade',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semestre'),
        ),
    ]
