# Generated by Django 4.2.1 on 2023-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_classroom_year_of_study_lesson_year_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='exam',
            field=models.CharField(blank=True, choices=[('exam 1', 'Exam 1'), ('exam 2', 'Exam 2'), ('exam 3', 'Exam 3'), ('exam 4', 'Exam 4')], max_length=120, null=True),
        ),
    ]
