# Generated by Django 4.2.1 on 2023-06-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_grade_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.CharField(choices=[('exam 1', 'Exam 1'), ('exam 2', 'Exam 2'), ('exam 3', 'Exam 3'), ('exam 4', 'Exam 4')], default='exam 1', max_length=120),
        ),
    ]
