# Generated by Django 4.1.6 on 2023-06-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='year_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.year_study'),
        ),
    ]
