# Generated by Django 4.2.1 on 2023-06-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_delete_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('descriptions', models.TextField()),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher')),
                ('year_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.year_study')),
            ],
        ),
    ]
