# Generated by Django 4.2.1 on 2023-06-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
