# Generated by Django 4.2.1 on 2023-07-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_timetable_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_p1', to='main.module'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_p2', to='main.module'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_p3', to='main.module'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_p4', to='main.module'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_p5', to='main.module'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_p6', to='main.module'),
        ),
    ]
