# Generated by Django 4.1.6 on 2023-07-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_exam_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_alert',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classroom'),
        ),
    ]
